### ISSUE TITLE
Include Windows in CI/CD

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/jetstream#121]
I wouldn't expect issues but we should test all command line tools on multiple platforms.

e.g.
https://github.com/nats-io/nsc/blob/master/.travis.yml

**Comment by ripienaar** [comment]
moved here where the CLI is, good call

**Comment by ripienaar** [comment]
done, these tests do a lot of actual running of the CLI and testing the outcomes, so I think we're good.

https://github.com/nats-io/jetstream/blob/85b863112b51cd0d797d2599bf8a65919b58b310/nats/nats_test.go#L215-L220

all passing on windows
