### ISSUE TITLE
queue sub on consumer yields no messages

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#124]
Setting up a push consumer:

```json
nats consumer info ORDERS MONITOR --json
{
  "name": "MONITOR",
  "config": {
    "delivery_subject": "monitor.ORDERS",
    "durable_name": "MONITOR",
    "start_time": "0001-01-01T00:00:00Z",
    "deliver_all": true,
    "ack_policy": "all",
    "max_deliver": -1,
    "replay_policy": "instant"
  },
  "state": {
    "delivered": {
      "consumer_seq": 11,
      "stream_seq": 11
    },
    "ack_floor": {
      "consumer_seq": 4,
      "stream_seq": 4
    },
    "pending": null,
    "redelivered": null
  }
}
```

If I subscribe to this with a queue subscriber I get no messages delivered to any queue subscriber

Should queue subscribers be supported on a push consumer output subject @derekcollison? seems to me like they should be

**Comment by derekcollison** [comment]
Thanks will take a look.

**Comment by derekcollison** [comment]
Fixed via https://github.com/nats-io/nats-server/commit/c8cabcbc0ef0e68acc54a77863e0a9c9234e48bc

**Comment by derekcollison** [comment]
Fixed via https://github.com/nats-io/nats-server/commit/68c29ee08d45bc9d055c4918f95e5563863305e7

**Comment by ripienaar** [comment]
Works a charm, thanks
