### ISSUE TITLE
deny streams that overlap with the API

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#137]
A stream with acknowledgement enabled that consumes topics `>` will cause havoc, it's +OK responses to JS API requests can come before API replies and cause responses to be invalid.

We should not allow stream subs that overlaps with the API - and if we choose to do so it should be without Ack

reported by @matthiashanel

**Comment by derekcollison** [comment]
ok understood what is going on for sure. Will think about it.

**Comment by matthiashanel** [comment]
@derekcollison, comments in this one #139 are related.

**Comment by derekcollison** [comment]
I went to write a simple test to disallow but I can see folks wanting to store all the API messages for audit, so want to make sure we enable that and not just disallow streams that overlap.

**Comment by ripienaar** [comment]
Isn’t that what the audit advisories are for? They include more details than just the api calls and can easily go to a stream.

**Comment by derekcollison** [comment]
Very good point, your right. Will add in restriction that generic add stream can not overlap with API. Thx.

**Comment by derekcollison** [comment]
ok so also just $JS.API, not $JS.>

**Comment by derekcollison** [comment]
ok implemented.
