### ISSUE TITLE
nats create stream does not expose noAck

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/jetstream#139]
There is no prompt for it. Help text does not specify it either (only allows turning it on, which seems to be default anyways)

IMHO the option should not exist. An App is going to wait. 
So disabling it here is going to cause issues.
Instead we should only reply when prompted by the app.

```
./nats -s 0.0.0.0:4222 stream create TOAST
? Subjects to consume toast.>
? Storage backend memory
? Retention Policy Limits
? Message count limit -1
? Message size limit 0
? Maximum message age limit -1
? Maximum individual message size -1
Stream TOAST was created

Information for Stream TOAST

Configuration:

             Subjects: toast.>
     Acknowledgements: true
            Retention: Memory - Limits
             Replicas: 1
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

            Messages: 0
               Bytes: 0 B
            FirstSeq: 0
             LastSeq: 0
    Active Consumers: 0

./nats -s 0.0.0.0:4222 stream create TOAST2 -h
usage: nats stream create [<flags>] [<stream>]

Create a new Stream

Flags:
...
      --ack                      Acknowledge publishes
...

12:35:36  ~/repos/jetstream/nats  master  ./nats -s 0.0.0.0:4222 stream create TOAST2 --ack=false
nats: error: unexpected false, try --help
 12:35:42  ✘ 1  ~/repos/jetstream/nats  master  ./nats -s 0.0.0.0:4222 stream create TOAST2 --ack
? Subjects to consume te
? Storage backend file
? Retention Policy Limits
? Message count limit -1
? Message size limit 0
? Maximum message age limit -1
? Maximum individual message size -1
Stream TOAST2 was created

Information for Stream TOAST2

Configuration:

             Subjects: te
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

            Messages: 0
               Bytes: 0 B
            FirstSeq: 0
             LastSeq: 0
    Active Consumers: 0

 12:35:50  ~/repos/jetstream/nats  master 

```

**Comment by ripienaar** [comment]
Boolean CLI options take —no-ack unfortunately the library they generate the CLI doesn’t show this clearly

**Comment by matthiashanel** [comment]
> Boolean CLI options take —no-ack unfortunately the library they generate the CLI doesn’t show this clearly

Yep, just tried that. it takes it. but it does not make it into help.

**Comment by ripienaar** [comment]
Yeah it’s also a pain to prompt for because you get basically a 3 state Boolean. 

Will see if I can turn it into a nil pointer Boolean which is really annoying in go

**Comment by matthiashanel** [comment]
No Rush, I basically filed this so it's not forgotten.
The option is a result of jetstream acking whenever there's a response subject, I believe the fix should be in not doing that.

**Comment by ripienaar** [comment]
@matthiashanel If I follow what you're saying you want JS not to ack receiving messages via the reply subject? How else would it ack receiving messages?

**Comment by matthiashanel** [comment]
@ripienaar , I assume things can still change while in technical preview. 
For starters I'd not use nc.Request(q.Topic, out, timeout) to receive an ack.
It forces the entire connection to use old style inboxes. 
I would add a call that does basically does what request does (create an inbox, subscribe, auto unsubscribe 1, publish request, s.next) but instead uses an inbox with a new prefix $JS._INBOX.
This would still be be compatible with the protocol.
Adding a helper say nc.RequestJSAck(...) would keep usage simple.
Jetstream would only respond if such an inbox was used.

To support publishrequest getting multiple answers, from nats clients as well as jetstream, I'd make the inbox name format known and add a call NewInboxWithAckResponse(), So that the client can create it's own subscriber etc...

**Comment by ripienaar** [comment]
While those would be interesting improvements one of the main driving forces for the JS design is to be “just nats” it has to fit in naturally with what people already know. 

We don’t want to create ways to do JS specific requests and that’s a feature imo. 

Re the inboxes - we have to use old style inboxes so JS know when interest is gone

**Comment by matthiashanel** [comment]
This is at the cost of requiring configuration that at best has to be set, at worst allows you to shoot yourself in the foot. 
Either way smth. new has to be learned, semantic overload of existing calls and thus new responses, or a new inbox soliciting a certain response (an inbox we could, by name design, make subject to permissions).
I just want to have brought it up.
