### ISSUE TITLE
Some API errors do not produce advisories

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#162]
Errors like these should probably also produce error advisories, what do you think @derekcollison 

https://github.com/nats-io/nats-server/blob/915876db61ea97a0346bf1a618cfe5ab39742205/server/jetstream_api.go#L369

**Comment by derekcollison** [comment]
Yes

**Comment by ripienaar** [comment]
https://github.com/nats-io/nats-server/pull/1353/files
