### ISSUE TITLE
Working with Jetstream

### ISSUE THREAD

**Issue by dioptre** [nats-io/jetstream#176]
Hi there,

I've been investigating working with Jetstream but as it's new I'm interested in what the team would recommend in working with aggregates/and processsing of data. It seems kafka/flink/spark/samza/ray/streamz all have little ecoverses but wondered if anyone had preferences here as to what could work well? Im especially interested in accumulating realtime statistics and sharing them at scale. Thinking something like a distributed dataframe. I was thinking nats, and flink would be good for this - but jetstream and maybe something you'd recommend would be better?

I do like the checkpointing that flink brings to the table.... but keen to hear your thoughts.

**Comment by ripienaar** [comment]
We do not have a canned solution at the moment, integrating with systems like the ones you mention is a priority though.
