### ISSUE TITLE
nats utility add possibility to use environment variables for tls

### ISSUE THREAD

**Issue by tpihl** [nats-io/jetstream#178]
Many of the config flags allow environment variables, but --tls* does not. 

It would help a lot to allow them also to be defined by environment variables to make it simpe set up environment with NATS_URL and TLS to allow command line without a long list of parms.

**Comment by ripienaar** [comment]
will do, thanks for the feature request

**Comment by ripienaar** [comment]
added NATS_CERT, NATS_KEY and NATS_CA environment vars

**Comment by tpihl** [comment]
Could we get a release of this (cherrypicked) (if the next version is not imminent)?

**Comment by ripienaar** [comment]
Right now its a bit tough to do a release as we're working on quite sweeping changes to the API so if possible I'd like to delay a bit
