### ISSUE TITLE
Consider the possibility of terminating messages ahead of time in NAK

### ISSUE THREAD

**Issue by tstenvi** [nats-io/jetstream#189]
The current specification for AckNak states that NAK’d messages will be retried. In addition to this behaviour, it would be beneficial with the option to explicitly terminate the message before the max retries runs out in the scenario where an invalid or unexpected message has been encountered in a service. Instead of acknowledging the message with an error message in the individual service, the termination through the NAK would ensure that an advisory of the occurrence would be published that can be read by a separate service for reporting and alerting purposes for instance.

**Comment by derekcollison** [comment]
So just to be on the same page, this would cancel all redeliveries correct?

**Comment by tstenvi** [comment]
Yes, exactly

**Comment by derekcollison** [comment]
So looking at this, can do an advisory fairly easily. Question I have is should we also have some discoverable state in case the advisory is missed?

**Comment by ripienaar** [comment]
The advisory would be the current delivery exceeded advisory since this is basically a short circuit to max deliveries reached?

We might add a field for reason to those. 

If people rely on them they need to go in a stream

**Comment by derekcollison** [comment]
We should have consumer sequence IMO as well as stream sequence.

I can re-use it if you want.

**Comment by derekcollison** [comment]
This issue has been addressed AFAIK.
