### ISSUE TITLE
Jetstream Cluster

### ISSUE THREAD

**Issue by dioptre** [nats-io/jetstream#195]
Hi there,

Seems like Jetstream doesn't have any work towards clustering yet? Would be good to understand and potentially help towards this. Not sure how usable this could be as a single machine, but loving the concept.

I wonder if you could easily setup a cassandra/druid/san data store for example? Cassandra supports tombstoning so might be a great choice. Though SAN/NAS might work right now esp if the stream is append only (apart from cleanup)?

Thanks
Andrew

**Comment by ripienaar** [comment]
At present while in Tech Preview we have a single server release, we are focussing on getting the programming model, behaviour and features right, we should ship a single server solution in NATS 2.2.0

That point signals a place where we are happy to say the API and behaviour is stable, at which point we'll turn our efforts to clustering with an eye for wider general GA that will include clustering around Q3

**Comment by dioptre** [comment]
Wonderful thanks, let me know if you guys need a hand or want to share in conversations.

**Comment by ripienaar** [comment]
At the moment we would really welcome any feedback on the features, behaviour and usability of the single node preview. Once merged to master fixing weirdness is much harder :)

**Comment by dioptre** [comment]
Interesting approach, I found that InfluxDB was completely unusable as they didn't consider query sizes in the beginning. Hoping and trusting you guys get the replays right. I really like the way the current beta is working (just hope it scales!).

**Comment by dioptre** [comment]
Also would hope you store the resulting data in Arrow. Everything of worth I know is moving to it in the next 6 months. Zero copy amongst clustered apps is going to be the next big thing.

**Comment by ripienaar** [comment]
This has been released
