### ISSUE TITLE
changed behaviour:: nats stream delete zzzz --force now asks for stream if zzzz doesn't exist

### ISSUE THREAD

**Issue by tpihl** [nats-io/jetstream#200]
I used nats stream delete <name> --force from bash-scripts to remove a stream before i re-created it. 

in 0.0.14 --force allowed me to not stop because is was the first time and it didnt exist (or i re-created nats-server).

in 0.0.16 it shows terminal gui and ask me to select another stream

**Comment by ripienaar** [comment]
I think 0.0.14 behaved the same as you describe 0.0.16 does:

```
ababfb225a0d:~# nats --version
0.0.14
```

```
ababfb225a0d:~# nats str ls
Streams:

        other
```

```
ababfb225a0d:~# nats str rm orders -f
? Select a Stream  [Use arrows to move, type to filter]
> other
```

**Comment by tpihl** [comment]
I was fairly sure it didn't ask in 0.0.14, but ok. 

So how do i construct a script that removes a stream/consumer/whatever no matter if it exist or not, without it stopping presenting interactive choices?

**Comment by ripienaar** [comment]
I think when there are no streams it doesn’t ask :)

I can add a flag I guess.

**Comment by tpihl** [comment]
would be great. because there can ofc be other streams

**Comment by tpihl** [comment]
Thinking about it, i think this is rather important. There should be a flag that prevent the "helping hand" to make sure a script doesn't get stuck. Also, if a command failed, it should return exitcode != 0 (maybe it already does).

This would allow an init container with a bash script to both check if a stream exists ('nats stream info <name>' would exit with zero to indicate that it already exist) instead of today showing other streamnames.

Or if nats knew if it was run interactively or in script.

**Comment by ripienaar** [comment]
without a TTY it exits already (though not exactly gracefully) :P

```
$ echo "nats str rm"|bash
? Select a Stream  [Use arrows to move, type to filter]
> ORDERS
nats: error: could not pick a Stream to operate on: EOF
$ echo $?
1
```

will add something

**Comment by ripienaar** [comment]
where --force is supported it will now exit with an error instead of prompting when set
