### ISSUE TITLE
emit advisories when a stream template creates a stream

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#201]
Seems to me that stream templates would be used by a type of application that want to dynamically add bundles of data to itself, but today there is no way other than template info to discover what streams exist.

Asking this info API at start to discover who is there now is fine, but at run time you want to be told when a new Stream managed by a specific template is made. It would be useful then to publish advisories when a template creates a new managed stream.

Published to `$JS.EVENT.ADVISORY.STREAM.TEMPLATE.CREATE_STREAM.<template name>`

```json
{
   "type": "io.nats.jetstream.advisory.v1.template_create_stream",
   "id": "....",
   "timestamp": "...",
   "template":"FOO",
   "stream": "FOO_managed_stream"
}
```

I can then create a stream to receive these advisories, at start I would:

 * create a ephemeral consumer where the events go that gets new only
 * query the stream template info for current streams
 * startup create all my stuff based on the info list of managed streams
 * as new advisories come in add new internal handlers for those managed streams

wdyt @derekcollison ?

**Comment by ripienaar** [comment]
Probably also need a delete advisory for a stream tbh

**Comment by derekcollison** [comment]
I think regardless of stream template you can send events on stream creation, deletion, consumers, etc. Maybe even API based deletes of messages in streams (not limits or expirations although that may be useful too, but with ranges)
