### ISSUE TITLE
is there options/config to at least limit jetstream RAM usage on server

### ISSUE THREAD

**Issue by tpihl** [nats-io/jetstream#21]
I would like to set some arbirtary max RAM for nats-server while allow unlimited disk space.

This would also be useful/needed for kubernetes resource limits and allocations.

**Comment by derekcollison** [comment]
This already exists internally but has not been surfaced as a config endpoint, etc for a server. We will surface something soon for sure, and its implemented that way already under the covers.

**Comment by ripienaar** [comment]
```
// enables jetstream, an empty block will enable and use defaults
jetstream {
    // jetstream data will be in /data/nats-server/jetstream
    store_dir: "/data/nats-server"

    // 1GB
    max_memory_store: 1073741824

    // 10GB
    max_file_store: 10737418240
}
```

note these are limits of the storage, not of all the various go routines and memory structures that support the operations of jetstream
