### ISSUE TITLE
jetstream  producer issue not going to stream

### ISSUE THREAD

**Issue by 2dev2** [nats-io/jetstream#244]
Hi..
we are using  docker image synadia/jsm:nightly means nats-server version 2.2.0-beta.15
and Git commit [bfe52fdb]
we are able to create stream, consumer and consume the the stream  by using jsm.go utility in golang source code .
But we are not able to send req/publish data to stream through publisher.

Is there any code examples are there so that we can publish our data to subject.
we are publishing data by using nats go client `natsConn.Publish("abc.p0.6, []byte(line.Text));`
and stream subject is configured for `abc.*`

from jetstream cli we are able to send request `nats req abc.scratch hello`

**Comment by 2dev2** [comment]
its under help needed label.. but we are not able to add label in github.

**Comment by ripienaar** [comment]
The subject `abc.*` means only `abc.x` not also `abc.x.y` if you want all subject below you need to use `abc.>`

**Comment by 2dev2** [comment]
sure..thanks a lot missed this one.
