### ISSUE TITLE
consumer heartbeats

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#250]
When a push consumer disconnects from the network due to bad network that consumer will just stop working and the client will have no way to determine this happened, there's no way to confirm it's valid and no way to recover from that scenario. The same scenario that led to https://github.com/nats-io/stan.go#connection-status 

We need a concept of a heartbeat so the consumer can get messages telling them things went bad, something like a `nil` body with a Header indicating heartbeat count or similar.

What I don't know is what kind of callback we'll fire or what we'll do in the absence of that heartbeat?

```
sub, err := nc.Subscribe(nats.NewInbox(), handler)
```

how does that communicate this failure and what happens when that failure happens? It has to be subscription specific, we don't want every user to (badly) implement the handling of this, I imagine we'll need some helper that:

 * Remembers creation parameters
 * Tracks the message sequences including whats been ack'd
 * Transparently recreates the consumer if it heartbeat fails using the tracked sequence as starting position

But the recreation is very problematic since we can't know about out of order deliveries due to redeliveries and so the simple scheme or subscribing to last acked+1 will cause duplicates. I can't think of a good design with what we have. 

But remembering how really painful this was in STAN to retrofit to existing code bases we need an answer for this during tech preview timeline

**Comment by derekcollison** [comment]
This was a bit about my desire to put in `how far behind` you are in the reply subject / metadata for delivered messages. This does not help with the very next one after the last, but can help quite a bit in some designs.

Question these sorts of things bring up is what will the application do with the information? Is it helpful or actually just more confusing. Not totally clear.

I do think adding in the last sequence known for the stream to delivered messages is important.

**Comment by ripienaar** [comment]
We will have to create a helper that observes these heartbeats and not expose them to the user, that recreates/resubscribes when there is issues.

Easy with durables they will do the right thing but ephemerals are a real pain you just dont know where to start

**Comment by derekcollison** [comment]
Not sure HBs are the right thing tbh.. And again, let's say we magically fire a callback that says you should be receiving messages but you aren't. What will the app do with that information?

**Comment by ripienaar** [comment]
How else will you tell the consumer he's getting no data because there's no new data vs no data because he is dead if not a heartbeat?

Just spitballing the first thing that come to mind, but we should provide something very roughly like this:

```go
sub, err := stream.NewEphemeralConsumer(jsm.FilterStreamBySubject("foo"), jsm.StartWithLastReceived(), handler)
```

`handler` gets called for every message just like `nats.Subscribe()` - handler not called for heartbeats - but the `NewEphemeralConsumer` will create something to monitor the absence of heartbeats and recreate up to last acked against the same inbox - this way the subscription continues subject to standard underlying nats connection retries.

**Comment by derekcollison** [comment]
How we do it is not as important, my question is what does the app do? Exit? Wait for NATS to self heal? In other words giving that information sometimes is not a good thing. And many times its wrong in one form or another and causes the app to do the wrong thing. Especially with NATS where it will try to self heal as best it can.

**Comment by ripienaar** [comment]
As I showed above, that's what is done with the heartbeats or absense thereof.

**Comment by ripienaar** [comment]
> Especially with NATS where it will try to self heal as best it can.

In this case the self heal leads to a broken consumer - the ephemeral timed out, no data will ever be received again.

**Comment by derekcollison** [comment]
Well for ephemerals we do wait a bit for them to come back and do not react too quickly, but how else would the server know to remove the state for it?

For a durable, does it do the right thing after a self heal? I agree it should if it does not.

**Comment by ripienaar** [comment]
durables are fine. 

An ephemeral just stop working if the interruption is longer than our grace period and the application has no way to detect that or recover.

**Comment by derekcollison** [comment]
The app of our layering could ping to JS and ask about the ephemeral consumer and if it detects the system is there but the consumer is gone resume where it left off.

**Comment by ripienaar** [comment]
For it to serve purpose the ping would have to be done regularly, say every n seconds after y seconds of no updates.

-> is consumer there
<- yes

vs

every n seconds after y seconds of no updates:

<- yes consumer is there 

heartbeats is 50% of the traffic.

**Comment by derekcollison** [comment]
The intelligence would be the same if server side or app side, only ask or HB in absence. But semantics are better on app side and spreads out the processing vs making server do everything.

**Comment by ripienaar** [comment]
ok, doesnt really matter for this issue which approach we take just now, as long as we agree its a thing thats needed

**Comment by derekcollison** [comment]
Agree that if possible ephemeral consumers should self heal, but I believe this is on the app side, not the server side.

**Comment by ripienaar** [comment]
With both above models the server need to support this? Or do you suggest the consumer just repeatedly call the existing is known consumer api for this?

**Comment by ripienaar** [comment]
My problem with the consumer side only approach is same as my problem with the nats streaming server behaviour, everyone has to get it right, every language binding has to get it right, 10s of library implementations and if you dont get it right from the get go the structure of your program changes so significantly later that it's effectively a rewrite.

https://github.com/nats-io/stan.go#connection-status is listed under "Advanced Usage" when in fact it's should be required for every single consumer ever to implement this else the system fails silently in a unrecoverable and undetectable manner.  It's a terminal failure in library design imo 

So in JetStream I think doing the right thing should be obvious and visible from day one.  If the server emits heartbeats its 1 implementation to get right and everyone who ever make ephemeral consumers discovers this need.

**Comment by derekcollison** [comment]
I agree client code needs to be correct in reference impl regardless if its receiving HBs or doing inactive polls to see if consumer still exists.

**Comment by ripienaar** [comment]
There are a few significant differences:

If the server sends HBs:

 * Clients will discover this feature and be actively prompted to use the correct approach
 * Clients, while having to behave correctly, have a much lower amount of code to manage
 * Server can handle this in a single place

If the client handles this entirely:

 * Clients have to find out from documentation, experience, past failures that this is required. Worst case scenario imo
 * Clients will then have to do quite large code reorgs to handle this scenario, just like it was with STAN
 * Clients have to do a whole lot of work just right - calling the API, possibly in go routines if those exist etc, would be hard to do on low spec machines
 * Servers have to pass all this through the API entrance
 * Huge load on future RBAC systems that will do access control to the API
 * Huge amount of API audit advisories, making this not 50% more traffic but a very large amount more. Every ephemeral consumer will be hitting this API regularly
 * Every client needs access to the API calls that can potentially leak information about other consumers that is none of their business

**Comment by ripienaar** [comment]
This has been done
