### ISSUE TITLE
overlapping templates

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#251]
Given 2 templates that overlap, both has the same config just different names:

```
{
  "name": "T1",
  "config": {
    "name": "_",
    "subjects": [
      "in.\u003e"
    ],
    "retention": "limits",
    "max_consumers": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 0,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "old",
    "num_replicas": 1
  },
  "max_streams": 100
}
```

Only the first creates a stream, I think this might be a side effect from where we now name streams just `in_x` for a message received on `in.x` rather than `T1_in_x` and `T2_in_x` since I think overlaps should work?

**Comment by derekcollison** [comment]
Given any subject `foo.bar` do we want to create 2 streams and store the message twice?

**Comment by ripienaar** [comment]
Yeah thought about this some more. We don’t allow overlapping streams. 

So we should also not allow overlapping templates I guess

**Comment by derekcollison** [comment]
Agree. Will queue up to fix.
