### ISSUE TITLE
deleting a stream with many consumers blocks API access for a long time

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#260]
I was testing memory and performance impact of 20k+ consumers on a stream and on deleting it the API was unavailable for minutes while the stream delete stopped each consumer.

Should probably be in a go routine and reply at the end of the go routine, otoh the long delete means no Request() will tend to wait that long for a response either

**Comment by ripienaar** [comment]
I also noticed after doing this delete that go routines did not drop significantly, I'll make a nicer reproduce but just for reference now:

```
goroutine 2765882 [sync.Cond.Wait, 165 minutes]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0000ca190, 0x36465220000026a)
        /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0000ca180)
        /usr/local/go/src/sync/cond.go:56 +0x9d
github.com/nats-io/nats-server/v2/server.(*Stream).waitForMsgs(0xc005766120)
        /go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.8-0.20200701221136-774da7f02108/server/stream.go:919 +0x4a
github.com/nats-io/nats-server/v2/server.(*Consumer).loopAndDeliverMsgs(0xc000ac4b40, 0xc0001bc400, 0xc00000c5a0)
        /go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.8-0.20200701221136-774da7f02108/server/consumer.go:1223 +0x175
created by github.com/nats-io/nats-server/v2/server.(*Stream).AddConsumer
        /go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.8-0.20200701221136-774da7f02108/server/consumer.go:477 +0xeb0
```

I have 808 of these active post delete

```
goroutine 2763472 [select, 171 minutes]:
github.com/nats-io/nats-server/v2/server.(*Consumer).updateStateLoop(0xc000635680)
        /go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.8-0.20200701221136-774da7f02108/server/consumer.go:812 +0x12e
created by github.com/nats-io/nats-server/v2/server.(*Stream).AddConsumer
        /go/pkg/mod/github.com/nats-io/nats-server/v2@v2.1.8-0.20200701221136-774da7f02108/server/consumer.go:479 +0xed5
``` 

718 of these

At present I have no active consumers in any stream

**Comment by ripienaar** [comment]
Plot thickens a bit - after the API eventually becomes available again i do not see the stream with the many consumers.  Server restart though brings it back with 8000 consumers active

I have to stop it and delete them by hand

**Comment by ripienaar** [comment]
```
package main

import (
	"fmt"
	"log"

	"github.com/nats-io/jsm.go"
	"github.com/nats-io/nats.go"
)

func panicIfErr(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	nc, err := nats.Connect("localhost")
	panicIfErr(err)

	str, err := jsm.NewStream("20k", jsm.FileStorage(), jsm.Subjects("in.20k.>"), jsm.StreamConnection(jsm.WithConnection(nc)))
	panicIfErr(err)

	for i := 0; i <= 20000; i++ {
		c, err := str.NewConsumer(jsm.DurableName(fmt.Sprintf("c%d", i)), jsm.FilterStreamBySubject(fmt.Sprintf("in.20k.%d", i)))
		if err != nil {
			log.Printf("Could not create consumer %d: %s", i, err)
			continue
		}

		log.Printf("Created %s", c.DurableName())
	}
}
```

Creating 20k consumers like that and just deleting the stream after reproduce this, locally its a lot faster I think my dev environment disks is a lot faster than my k8s cluster (lols).  

But even locally it deletes exactly 1024 consumers before something goes wrong, the stream is deleted from the api till next restart then its back...after this failed delete ^C doesnt work either of course.

Here are 3 startups after issuing the stream delete and waiting for the API to become responsive again:

```
[18257] 2020/07/13 14:40:08.602343 [INF]   Recovering 18977 Consumers for Stream - "20k"
[18432] 2020/07/13 14:41:07.327812 [INF]   Recovering 17953 Consumers for Stream - "20k"
[18530] 2020/07/13 14:41:49.730417 [INF]   Recovering 16929 Consumers for Stream - "20k"

**Comment by ripienaar** [comment]
This is the cause:

https://github.com/nats-io/nats-server/blob/8312f3fb6d34135ca3b65955950f60e492d19342/server/consumer.go#L1645

We publish many advisories into the sendq

But before we get here we send a nil which stops processing the senq

https://github.com/nats-io/nats-server/blob/8312f3fb6d34135ca3b65955950f60e492d19342/server/stream.go#L979

so the sendq goes full (its 1024 big) and the delete process hangs forever

**Comment by ripienaar** [comment]
We probably can skip consumer notifications if deleting a stream fwiw

**Comment by derekcollison** [comment]
Thanks, will fix it sometime this week.

**Comment by derekcollison** [comment]
You still want to not send advisories for the consumers?

**Comment by ripienaar** [comment]
I don't think they are needed if the stream is being deleted

**Comment by derekcollison** [comment]
Right now I left them in..

**Comment by ripienaar** [comment]
@derekcollison that seems to work a lot better, i dont see periods of API being inacessible while this run, just ```[::1]:33682 - cid:8 - Readloop processing time: 8.357308539s``` which isnt unexpected

**Comment by derekcollison** [comment]
ok so we should probably look and see if we have lots of consumers and if so move to go routine. Should I merge this one and do that one separate or all in this one?
