### ISSUE TITLE
Stream Templates format

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/jetstream#276]
I have a use-case where multiple k8s clusters will write to a nats instance. Imagine subjects like

```
k8s.c1.pods
k8s.c1.services
k8s.c2.pods
k8s.c2.services
```

Is it possible to define a steam template that will generate 2 streams like 

```
k8s.c1
k8s.c2
```

I want to do this so that I can enforce a per k8s level stream limits and retention policy.

**Comment by ripienaar** [comment]
Hmm, we do not support doing that at the moment, what we support would end up with streams like `k8s_c1_pods` and `k8s_c1_services`.

I think your use case is interesting though and probably something we'd run into regularly so might be something we want to support.  What do you think @derekcollison ?

**Comment by derekcollison** [comment]
I think you could be saying the template subject is `k8s.*.>`

**Comment by ripienaar** [comment]
Will try that, my quick read of the code didn’t pick that behaviour up but will give it a go :)

**Comment by lheiskan** [comment]
This would be useful for us as well, are there any additional thoughts about enabling something like this? Dereks suggestion above seems quite straight forward, and having such support would solve our use case.

**Comment by ripienaar** [comment]
I'll close this, we're not sure what we'll do with templates and they are not supported in clustering, the whole topic needs a rethink much later than this ticket raises
