### ISSUE TITLE
What does it mean to be GDPR compliant deletion?

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/jetstream#277]
`$JS.API.STREAM.MSG.DELETE.*` - Deletes a specific message in the Stream by sequence, useful for GDPR compliance

Can you please help me understand what GDPR compliance issue you are talking about here?

**Comment by ripienaar** [comment]
Many streaming products - including nats streaming server - are append only and can only expire messages based on limits. 

If you set it to keep a message for a year it’s impossible to remove it. Data privacy laws require users are able to remove their data on demand from your systems. Not just GDPR but many countries have similar systems. 

Being able to delete a message mid stream while maintaining overall stream integrity is what this feature is about.

**Comment by tamalsaha** [comment]
Thanks! I understand.
