### ISSUE TITLE
create reports based on server stats

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#282]
Should be able to get a table report of:

 * Accounts
   - [x] How many connections
   - [x] Cumulative bytes in/out
   - [x] Cumulative messages in/out

 * Connections
   - [x] Bytes in/out
   - [x] Messages in/out
   - [x] Connection duration

 * Leafnodes
   - [ ] Bytes in/out
   - [ ] Messages in/out
   - [ ] Connection duration

 * General
   - [x] reverse sort

Sortable by in ways that make sense

What else @derekcollison ?

**Comment by derekcollison** [comment]
This looks good to start..

**Comment by ripienaar** [comment]
added nats `server report connections` and `nats server report accounts`

**Comment by derekcollison** [comment]
These are very helpful!

**Comment by ripienaar** [comment]
Will close this one, we dont have leaf reports but I think thats fine for now
