### ISSUE TITLE
Overhead of stroing a message

### ISSUE THREAD

**Issue by laszbalo** [nats-io/jetstream#307]
Hi,

just wondering about how many extra bytes get stored when saving a message to disk.
Also, the message body is not base64 encoded when serialized, only when sent over the wire in response to an API request. Am I right?

Could somebody please explain this, provide a link to the source or add the answer to the documentation?

**Comment by ripienaar** [comment]
It's easy to test yourself-we do not store the messages base64 encoded and neither do we transmit them base64 encoded unless you access the stream msg get api.

4379 messages of 512000 bytes each takes 2242237751 on disk.  Note though that we allocate storage in 67077502 byte blocks so the discrepancy could be an empty block.

So the per message overhead is very low

**Comment by laszbalo** [comment]
Thanks for your answer. In your example the added metadata is negligible to the size of a single message(512 000 bytes). In my case, however, the messages are in the range of 30-70 bytes. That's why I was curious about the size of the metadata.

Did a search and found this function:
[fileStoreMsgSize](https://github.com/nats-io/nats-server/blob/f9fd8bafff41cc50135ef19b20095f78cf7f7305/server/filestore.go#L1623)

Just put it here if somebody is interested:

Currently the number of bytes required to store a message depends on three things:

1. length of the message
2. length of the name of the subject
3. extra headers

In the case of no headers, this code applies:
```golang
uint64(22 + len(subj) + len(msg) + 8)
```

Therefore if I send the `hello` message on the `greetings` subject without headers
```shell
$ nats req greetings hello
```
Jetstream will use 39 (22 + 9 + 8) bytes of metadata to store the 5 bytes long `hello` message.

Currently it seems a good idea to avoid long subject names if one has to deal with small messages.

**Comment by ripienaar** [comment]
Hello. Thanks for that detail, yes I intended to do an update about the short message long subject situation but got side tracked. 

Might add a section to the docs covering this. So will reopen the issue.

**Comment by ripienaar** [comment]
https://github.com/nats-io/jetstream/pull/310
