### ISSUE TITLE
Interest based retention holds messages when there are no interest

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#314]
Given an INTEREST based stream with no consumers:

```json
{
  "config": {
    "name": "INTEREST",
    "subjects": [
      "js.in.interest"
    ],
    "retention": "interest",
    "max_consumers": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 0,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "old",
    "num_replicas": 1,
    "duplicate_window": 120000000000
  },
  "state": {
    "messages": 0,
    "bytes": 0,
    "first_seq": 0,
    "first_ts": "0001-01-01T00:00:00Z",
    "last_seq": 0,
    "last_ts": "0001-01-01T00:00:00Z",
    "consumer_count": 0
  }
}
```

I'd expect no messages to be kept in the stream - there's no interest. Publishing to the stream does retain the messages though and if I add a consumer later they are delivered.

```json
  "state": {
    "messages": 3,
    "bytes": 135,
    "first_seq": 1,
    "first_ts": "2020-08-28T09:44:26.405034021Z",
    "last_seq": 3,
    "last_ts": "2020-08-28T09:44:27.79652116Z",
    "consumer_count": 0
  }
```

First reported in https://github.com/nats-io/jetstream/issues/312 by @jon-whit

**Comment by ripienaar** [comment]
What do you think about this? Seems to me interest based should not be keeping any messages when no consumers exist?

**Comment by jon-whit** [comment]
@ripienaar just my two cents.. The current documentation leads developers to believe that if the Retention Policy is `interest` based, then the messages will not be kept unless there is an active consumer.

So either the documentation needs to change, or the behavior needs to match the documentation.

**Comment by ripienaar** [comment]
Yes, this issue is to either fix the bug or figure out what the intended behaviour is so we can fix the docs :)

**Comment by derekcollison** [comment]
This sounds like a bug, will fix.

**Comment by ripienaar** [comment]
I was doing some testing for #351 and noticed the messages are again/still retained:

```
{
  "config": {
    "name": "interest",
    "subjects": [
      "js.interest"
    ],
    "retention": "interest",
    "max_consumers": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 0,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "old",
    "num_replicas": 1,
    "duplicate_window": 120000000000
  },
  "state": {
    "messages": 17804,
    "bytes": 9845612,
    "first_seq": 182197,
    "first_ts": "1970-01-01T00:00:00Z",
    "last_seq": 200000,
    "last_ts": "2020-10-22T14:57:32.423686606Z",
    "consumer_count": 0
  }
}
```

no consumers, messages are kept.

**Comment by derekcollison** [comment]
How were the messages loaded into the stream?

**Comment by ripienaar** [comment]
resolved
