### ISSUE TITLE
Readme Discussion Items Issues

### ISSUE THREAD

**Issue by somombo** [nats-io/jetstream#318]
(if this hasn't all already been done) I'd like to propose that for each of the discussion items listed in the main readme (i.e. https://github.com/nats-io/jetstream#discussion-items),
a Github Issue be opened up and the corresponding links to those issues be included in each of the subheadings for those items.

This will make it easy for us to find how we can contribute discussions regarding those issues and will also publicly centralize those discussions in an "RFC" kind of way

**Comment by ripienaar** [comment]
Agree, we're moving to a new project management method that might result in these thigns being more visible and public, we need a bit of time though :)

**Comment by ivorscott** [comment]
Enable Github discussions.

**Comment by ripienaar** [comment]
Closing this, this has all been merged into core nats and we prefer slack.  This whole repo is being shut.

**Comment by somombo** [comment]
> Closing this, this has all been merged into core nats and we prefer slack. This whole repo is being shut.

@ripienaar could you like the PR or issue on core nars where this has all been merged? .. i can't find it

**Comment by ripienaar** [comment]
Well, I mean the entire JetStream feature has been merged to master and released as 2.2.x, remainig items are now to be via new issues.  The "discussion items" in this document were some just old, or internally discussed and implemented/rejected.

We're past the Tech Preview so we're moving toward shutting this repo down entirely.

**Comment by somombo** [comment]
Okay, for anyone else who finds this useful:

- https://github.com/nats-io/nats-server/releases/tag/v2.2.0
- https://docs.nats.io/jetstream/jetstream

Thanks
