### ISSUE TITLE
How to use `NATS Authorization` for _Jetstream_ Specific feature 

### ISSUE THREAD

**Issue by masudur-rahman** [nats-io/jetstream#319]
I was reading about `NATS Authorization` from [this](https://docs.nats.io/nats-server/configuration/securing_nats/authorization#variables) blog. Here, I came to know how to authorize any user to publish or subscribe to any subjects.

```
ADMIN = {
  publish = "*"
  subscribe = ">"
}
```
With the above configuration, I could establish a connection which can publish or subscribe to any subject. But while I tried to create a _STREAM_ named `ORDERS`, I got the following error -

> Unexpected NATS error from server nats://127.0.0.1:4222: nats: Permissions Violation for Publish to "$JS.API.STREAM.CREATE.ORDERS"

I was wondering how I can setup my server configuration file so that I can create _STREAM_ and _CONSUMER_.

**Comment by ripienaar** [comment]
Can you please show the whole config and then what user you connect as from the CLI? (Show cli command)

**Comment by masudur-rahman** [comment]
Whole configuration for running nats server: 
```go
opts := &natsd.Options{
	JetStream:  true,
	StoreDir:   dir,
	Host:       "localhost",
	Port:       4222,
	LogFile:    "/dev/stdout",
	Trace:      true,
	ConfigFile: "server.conf",
}
```
Additional configuration: 
```
// server.conf

authorization: {
  timeout : 10
  super_user = {
    publish = "*"
    subscribe = ">"
  }
  users: [
    { user: admin, password: admin, permissions: $super_user }
  ]
}
```
My CLI command for create ORDER:
```console
$ nats str add ORDERS --subjects "ORDERS.*" --ack --max-msgs=-1 --max-bytes=-1 --max-age=1y --storage file --retention limits --max-msg-size=-1 --discard old --user=admin --password=admin
16:55:03 Unexpected NATS error from server nats://127.0.0.1:4222: nats: Permissions Violation for Publish to "$JS.API.STREAM.CREATE.ORDERS"
nats: error: could not create Stream: context deadline exceeded
```

**Comment by ripienaar** [comment]
Does it work with this config if you use the server binary and not embedded ?

**Comment by masudur-rahman** [comment]
I didn't try with the server binary. I started nats server by Go code.

**Comment by ripienaar** [comment]
Yes, I can see that. I don’t think how you do it parses there configuration file. 

Please try the server binary

**Comment by masudur-rahman** [comment]
My whole configuration file:
```
authorization: {
  timeout : 10
  super_user = {
    publish = "*"
    subscribe = ">"
  }
  default_user = {
    subscribe = "PUBLIC.>"
  }
  sender = {
    publish = "ORDERS.>"
    subscribe = ">"
  }
  default_permissions: $default_user

  users: [
    { user: admin, password: admin, permissions: $super_user }
    { user: alice, password: foo, permissions: $sender }
  ]
}
```

It parses the config file. I tried to publish some message to subject `ORDERS.processed` using `--user=alice --password=foo`, it worked. But when I changed the subject to something else like `MONITOR.processed`, it didn't pass the authorization.
> I don’t think how you do it parses there configuration file.

**Comment by ripienaar** [comment]
`publish = "*"` means publish to only "X" or "Y" but not "X.X" or X.Y.Z

**Comment by masudur-rahman** [comment]
While creating _STREAM_ it basically publishes some message to a channel `"$JS.API.STREAM.CREATE.ORDERS"`.  As I set `publish = "*"`, it couldn't send message to that channel due to authorization error.

Now I set `publish = ">"` as you suggested, _STREAM_ creation is working fine now.

Thank you @ripienaar.
