### ISSUE TITLE
nats-sub client not connecting

### ISSUE THREAD

**Issue by cliffburdick** [nats-io/jetstream#320]
Hi, when I use the nats-sub client, it reports that it can't connect to the server, but if I use "nats pub", it works fine. Is this expected?

```
nats-box:~# nats-sub -s nats://nats:4222 mysubject
nats: no servers available for connection
nats-box:~# nats sub -s nats://nats:4222 mysubject
20:25:37 Subscribing on mysubject
```

**Comment by ripienaar** [comment]
It's not expected no, can you see if maybe NATS_URL environment variable is set to something?

**Comment by ripienaar** [comment]
I'd add that we are moving to using `nats` only, the nats-sub and friends are a bit bare bones and lacks many features, if `nats` work for you, use that :)

We have not however made fundemental changes that means nats-sub now cant work anymore at least to the same extend that it always has, it's probably something environmental going on

**Comment by cliffburdick** [comment]
> It's not expected no, can you see if maybe NATS_URL environment variable is set to something?

Hi @ripienaar, it appears to be set already:
```
nats-box:~# export|grep NAT
export NATS_CONFIG_HOME='/nsc/config'
export NATS_URL='jetstream:4222'
```

I did an unset on it, and that is working:
```
nats-box:~# nats-sub -s nats://nats:4222  mysubject
Listening on [mysubject]
```

Closing. Thanks!
