### ISSUE TITLE
Load Streams In NATS Config

### ISSUE THREAD

**Issue by cliffburdick** [nats-io/jetstream#321]
This is a feature request.

Currently the ways to set up NATS streams are nats CLI, terraform, and GH actions. When deploying in an environment where things publish into NATS after it's up, but before the streams are created, there's a race condition where those messages won't be consumed into the stream. It would be useful if we could specify the streams inside of the nats.conf configuration so that clients couldn't publish successfully before at least some streams are statically created.

**Comment by ripienaar** [comment]
Short answer: Where we are today with a single server I agree this seems like a obvious oversight and something we should do.  This is quit a complicate situation here though with many impacting design decision. I think we do need file based, but how that is done depends a lot on upcoming work so we are likely to add it a bit later.

Long answer:

JS is multi tenant meaning 1 NATS server can host multiple entirely seperate instances of JS for different accounts each with own limits, behaviours, streams etc in isolation.  Already this means we have a lot of different ways to configure JS - files, jwt,account server etc.

Further we are planing the storage layer in JS to be much less rigid than in STAN meaning you will think more about the storage as opaque pool of resources and each stream will elect a server who manage it, this changes the equation a bit wrt confguration and observability etc. We want the resource pools to be more flexible and easier to scale up/down, this will have impact on how we configure things and a simple file based approach might not suffice.

Further as with our NATS 2.0 account based system we think accounts have to be self service where once a server owner have enabled JS within an account the account owners - without needing access to the servers - must be able to administer their own sandbox within limits the server operator has set

How all of this is implemented and impact on configuration is something we are stil working on.

So while a configuration file might seem interesting, it wont help a whole lot in a multi tenant scenario and with the server resource pooling you'd need to be very careful how and in what order and in what kind of time difference configuration files are managed on the cluster as a whole something that will be remakably difficult with a traditional configuration managed system.  It could also have knock on affects on what features we can expose in the API on such configured streams.

So we think the API based approaches are for the moment what we can support safely (ie. that we wont just demand you change how its done soon), and once we know enough and know we can do so in a single go we'll look at configuration files and if it makes sense.

Meanwhile we're adding CRDs for kubernetes, which I agree in STAN wasn't that useful, but for how JetStream will shape up I think will work really well in that world.

**Comment by tpihl** [comment]
I never saw this as an issue since if the stream capture is important, I will anyhow require an ACK (or retry).

The ACK will be missing until the stream is fully set up. 

/T

**Comment by ripienaar** [comment]
> I never saw this as an issue since if the stream capture is important, I will anyhow require an ACK (or retry).
> 
> The ACK will be missing until the stream is fully set up.

Strong agree, if your messages matter you have to process ACKs.  Late configuration is not the only thing that can cause a stream to be unavailable
