### ISSUE TITLE
work queue sequences oddness

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#324]
I have a work queue, after some time some messages were removed after ack and 1 is there waiting to be consumer:

```json
% nats s info WORK -j|jq .state
{
  "messages": 1,
  "bytes": 44,
  "first_seq": 3,
  "first_ts": "2020-09-04T09:46:26.53125897Z",
  "last_seq": 3,
  "last_ts": "2020-09-04T09:46:26.53125897Z",
  "consumer_count": 1
}
```

If I ack the message, I get this:

```json
{
  "messages": 0,
  "bytes": 0,
  "first_seq": 4,
  "first_ts": "1970-01-01T00:00:00Z",
  "last_seq": 3,
  "last_ts": "2020-09-04T09:46:26.53125897Z",
  "consumer_count": 1
}
```

The weird thing is first_seq > last_seq

**Comment by derekcollison** [comment]
That has been the behavior since the beginning.

**Comment by derekcollison** [comment]
When a used stream empties first will be last+1.

**Comment by ripienaar** [comment]
Yeah I realise its not new, just noticed it now, seems weird but makes sense as you explain it
