### ISSUE TITLE
duplicate tracking should reset on stream purge

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#340]
dedupe works...

```
$ nats pub js.in.testing 1 -H Msg-Id:3 -H Foo:Bar
18:43:11 Published 1 bytes to "js.in.testing"
$ nats str info TESTING -j|jq .state.messages
1
$ nats pub js.in.testing 1 -H Msg-Id:3 -H Foo:Bar
18:43:16 Published 1 bytes to "js.in.testing"
$ nats str info TESTING -j|jq .state.messages
1
```

but if I purge it the next message on that Msg-Id should be accepted right?

```
$ nats str purge TESTING
$ nats pub js.in.testing 1 -H Msg-Id:3 -H Foo:Bar
$ nats str info TESTING -j|jq .state.messages
0
```

Guess it's debatable but for me seems like purge should reset it, wdyt @derekcollison

**Comment by derekcollison** [comment]
I don't think purge should reset that IMO, same as if a message expires. However, interested in thoughts from @ColinSullivan1 and @kozlovic here.

**Comment by kozlovic** [comment]
Tough one. For expiration I would say no (msgID not removed from de-dup list), in case we have a really small expiration window and an app has been network-partitioned for a bit longer. However for purge, I would think that this is an admin process and someone really wants to reset the state. Imagine a situation where message IDs are not simply random unique bytes, but have a correlation to the content, you would basically be unable to restart the publish of all messages after a purge.

**Comment by derekcollison** [comment]
Agree, I was going off of the path of least surprise, which is any user who sends a message with an ID and gets and ack, if you send the same ID will fail. User can change ID to push message through though after a purge.

**Comment by ripienaar** [comment]
How would this producer know this happened? What would trigger him to change the ID? Publishing a duplicate does not fail. It returns some metadata about the publish that indicates the duplicate but no error. 

In the nats.go api you say people dont need access to the metadata and we have no way to communicate that a duplicate was handled there

**Comment by derekcollison** [comment]
You raise a good point here. I am not sure I know the right answer, so if we feel strongly about it either way let's go with that and just make sure we document well.

**Comment by ripienaar** [comment]
@derekcollison you had more time to think on this one? Seems like we're floating towards should-reset?

**Comment by derekcollison** [comment]
I do not have a strong opinion here, so if we think we should reset I am ok with that behavior.

**Comment by ripienaar** [comment]
Lets reset then :)

**Comment by derekcollison** [comment]
ok will do, will post up PR in a bit.
