### ISSUE TITLE
Net Core Client Library?

### ISSUE THREAD

**Issue by david-ernstsson-stratsys** [nats-io/jetstream#366]
I didn't find a better place to post/find answer to my general question, if there is I do apologize

- Are you planning to release a client library for .net (standard/core) together with the release of jetstream into core nats? Or will that be more of "later"?
- Roadmap says Q4 2020 for jetstream in core nats so I'll assume thats still correct :)

(We have a project were we have decided to migrate from our old message broker to nats and are trying to figure out if we should use stan or wait for nats jetstream to be released with cluster support. If possible I'm looking for some kind of guidance where in time things might be released)

Best regards, David

**Comment by ripienaar** [comment]
Yes we are adding light touch helpers to the core libraries that we support, however realise these are just helpers, using JetStream does not require specific support in your client libraries.

**Comment by ripienaar** [comment]
I believe this is in flight or will soon be, refer to commits in the .Net repo
