### ISSUE TITLE
go get issue due to deps

### ISSUE THREAD

**Issue by wallyqs** [nats-io/jetstream#371]
we need to update the go modules and tag a release:
https://github.com/HdrHistogram/hdrhistogram-go/issues/32

**Comment by ripienaar** [comment]
Probably need to add `replace github.com/codahale/hdrhistogram => github.com/HdrHistogram/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd` since its a indirect dependency

**Comment by ripienaar** [comment]
(that hash will need a update)

**Comment by ripienaar** [comment]
https://github.com/nats-io/jetstream/pull/372
