### ISSUE TITLE
Is it possible to implement request-reply model using jetstream

### ISSUE THREAD

**Issue by reidlai** [nats-io/jetstream#393]
Same as subject.  Any hints there?

**Comment by ripienaar** [comment]
At the moment we do not store the reply subject in a jetstream message, you can however use a header of your own choosing and have your application respond to the subject in that header.

Given the potentially long period of time between a message being published and it being handled it might be awkward

**Comment by ripienaar** [comment]
Closing this, JetStream is in GA nothings changed from my last update here
