### ISSUE TITLE
purge enhancements

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#398]
Today Purge just deletes everything, I want to be able to achieve a few more things.

First, purge up to a specific stream sequence - this will let me programatically rollup a stream by publishing a new message thats the rollup/summary and delete published-1, or just do stream maintenance on wildcards.  `Purge(seq)`

Second, it would be good if I can do Purge up to a specific sequence but only for those matching a specific subject in a wildcard stream.  This will let me store for example lots of related items like configuration and then rollup programatically specific subsets of the stream. `Purge(subject, seq)`

Finally using the 2nd above, I would like to publish a message with something like `Nats-Rollup:1` which will take the subject the message came in on, store this message and delete everything before that message received on that subject.  For non wildcard streams obviously that implies the first behaviour, just purge up to before the just published message.

You mentioned recently you dont know what we'd do with current consumers who are consuming these streams - I am not entirely sure, but I presume we already do something sane for a normal purge, right?

**Comment by tpihl** [comment]
This is spot on, this rollup (a aggregate or snapshot in my book) vacates the need of the earlier messages (but i may want to do this in more than one step).
* create the roll-up and publish it (either on a parallel subject or if we have added optimistic locking [not a fan] in the same subject)
* have some other process ensure that all msg in subject that was contained in the rollup has been sent to long-term-storage (that durable subscriber have acked the last msg in the roll-up) and then purge subject up to and including that last msg.
* so in parallel there is a subscriber and some function that will write long-term storage with some good packing/blocksize so the information isn't lost.

**Comment by ripienaar** [comment]
Yeah agree - so I want both option 2 and 3. 2 to facilitate your flow and 3 for where needs are less strict.

**Comment by ripienaar** [comment]
Closing as JS is now GA, we have this on roadmap
