### ISSUE TITLE
Working with multiple streams

### ISSUE THREAD

**Issue by spiderman0510** [nats-io/jetstream#402]
I am following work queue example to build my project, here is my code
```
func (s *JetstreamHandler) Emit(e Event) {
	jsonString, err := json.Marshal(e)
	if err != nil {
		log.Fatal(err)
		return
	}
	for _, stream := range s.streams {
		if stream.Name() == string(e.Type) {
			consumerNames, err := stream.ConsumerNames()
			if err  != nil {
				log.Error(err)
				continue
			}
			for _, consumerName := range consumerNames {
				consumer, err := stream.LoadConsumer(consumerName)
				if err  != nil {
					log.Error(err)
					continue
				}
				if err = s.nc.Publish(consumer.FilterSubject(), jsonString); err != nil {
					log.Error(err)
					return
				}
			}
		}
	}
}
func (s *JetstreamHandler) Listen() {
	go func() {
		for {
			for _, stream := range s.streams {
				consumerNames, err := stream.ConsumerNames()
				if err  != nil {
					log.Error(err)
					continue
				}
				for _, consumerName := range consumerNames {
					consumer, err := stream.LoadConsumer(consumerName)
					if err  != nil {
						log.Error(err)
						continue
					}
					s.processNextMessage(stream.Name(), consumer.DurableName(), s.mgr)
				}
			}
		}
	}()
}

func (s *JetstreamHandler) processNextMessage(stream, consumer string, mgr *jsm.Manager) error {
	msg, err := mgr.NextMsgContext(context.Background(), stream, consumer)
	if err == nats.ErrTimeout {
		return nil
	}
	if err != nil {
		return err
	}
	
	log.Infof("Got event: %#v", msg.Data)
	
	return msg.Respond(nil)
}
```
My general idea that i will publish message to a stream by calling Emit func. and Listen func will process message. However i just have only first message, my application always stop at line: msg, err := mgr.NextMsgContext(context.Background(), stream, consumer). cant process more message anymore
What should i do with this issue

**Comment by spiderman0510** [comment]
> I am following work queue example to build my project, here is my code
> `func (s *JetstreamHandler) Emit(e Event) {
> jsonString, err := json.Marshal(e)
> if err != nil {
> log.Fatal(err)
> return
> }
> for _, stream := range s.streams {
> if stream.Name() == string(e.Type) {
> consumerNames, err := stream.ConsumerNames()
> if err != nil {
> log.Error(err)
> continue
> }
> for _, consumerName := range consumerNames {
> consumer, err := stream.LoadConsumer(consumerName)
> if err != nil {
> log.Error(err)
> continue
> }
> if err = s.nc.Publish(consumer.FilterSubject(), jsonString); err != nil {
> log.Error(err)
> return
> }
> }
> }
> }
> }
> func (s *JetstreamHandler) Listen() {
> go func() {
> for {
> for _, stream := range s.streams {
> consumerNames, err := stream.ConsumerNames()
> if err != nil {
> log.Error(err)
> continue
> }
> for _, consumerName := range consumerNames {
> consumer, err := stream.LoadConsumer(consumerName)
> if err != nil {
> log.Error(err)
> continue
> }
> s.processNextMessage(stream.Name(), consumer.DurableName(), s.mgr)
> }
> }
> }
> }()
> }
> 
> func (s *JetstreamHandler) processNextMessage(stream, consumer string, mgr *jsm.Manager) error {
> ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
> defer cancel()
> msg, err := mgr.NextMsgContext(ctx, stream, consumer)
> if err == nats.ErrTimeout {
> return nil
> }
> if err != nil {
> return err
> }
> 
> ```
> log.Infof("Got event: %#v", msg.Data)
> 
> return msg.Respond(nil)
> ```
> 
> }`
> 
> My general idea that i will publish message to a stream by calling Emit func. and Listen func will process message. However i just have only first message, my application always stop at line: msg, err := mgr.NextMsgContext(ctx, stream, consumer). cant process more message anymore
> What should i do with this issue

**Comment by ripienaar** [comment]
Using `NextMsgContext()` means it wont timeout until the context exits, I guesst you use a mode based on a timeout so that your `processNextMessage()` doesnt wait forever.

**Comment by spiderman0510** [comment]
Hi @ripienaar ,
Yes, you're right, but i changed my code following:
```
ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
defer cancel()
msg, err := mgr.NextMsgContext(ctx, stream, consumer)
```
I realized that, NextMsgContext function will listen on specific stream, process and wait until timeout
In my case, 2nd steam need to wait 1st stream finished. so my application get stuck a minute then process 2nd stream. are there any way to process message on multiple stream at same time?

**Comment by ripienaar** [comment]
You'd need to use go concurrency features to have go routines polling concurrently, or use push mode and normal nats Subscribe which is by default async

**Comment by spiderman0510** [comment]
Thanks @ripienaar , i will apply your suggestion and report back here

**Comment by spiderman0510** [comment]
Hi @ripienaar , my issue has been solved. But i have a another question, how can i reload list of stream and consumer.
I start jetstream server by command line: ./nats-server -js. Then if i stop it, all streams are gone.

**Comment by ripienaar** [comment]
If you start it without configuration or storage directory specified it will pick a random storage directory.

Either make a configuration or pass `-sd` flag.
