### ISSUE TITLE
Stream not being stored (file) after first run

### ISSUE THREAD

**Issue by delaneyj** [nats-io/jetstream#403]
Have have a region like 
```go
        js, err := conn.JetStream()
	if err != nil {
		return nil, xerrors.Errorf("no jetstream : %w", err)
	}
	commandsStream, err := js.AddStream(&nats.StreamConfig{
		Name:         "COMMANDS",
		Subjects:     []string{"COMMANDS.*"},
		NoAck:        false,
		Retention:    nats.LimitsPolicy,
		Duplicates:   15 * time.Minute,
		Storage:      nats.FileStorage,
		Discard:      nats.DiscardOld,
		MaxAge:       0,
		MaxConsumers: -1,
		MaxBytes:     -1,
		Replicas:     1,
	})
	if err != nil {
		return nil, xerrors.Errorf("can't add commands stream : %w", err)
	}
	log.Print(pretty.Sprint(commandsStream))
	log.Print(commandsStream.Created.Format(time.RFC3339))

	for i := uint64(0); i < 10000; i++ {
		msg := fmt.Sprintf("{\"foo\",%d}", time.Now().UTC().Unix())
		ack, err := js.Publish("COMMANDS.foo", []byte(msg), nats.ExpectLastSequence(0+i))
		if err != nil {
			return nil, xerrors.Errorf("can't publish : %w", err)
		}
		log.Print(ack, msg)
	}
```

And if you run it, you get messages stored, running again you get a `wrong last sequence: 10001` as expected.  Restarting the server to verify it all got saved; if you update to `nats.ExpectLastSequence(10001+i))` it works again as expected dumping message in and the last ack printing `&{COMMANDS 20001 false}`.  So far so good, but if I restart the server and run again it works without updated the last sequence.... its still at `10001` and doesn't appear to change the filesize of `COMMANDS/msgs/1.blk` when I check.  

Also I did try commenting out the `AddStream` after the first run with no luck and looking at the metadata it looks like the call is actually works like an upsert.

I'm sure its just me missing something as this is very new to me.

**Comment by ripienaar** [comment]
Might be better in the nats.go repo, maybe @wallyqs can investigate this one

**Comment by delaneyj** [comment]
Thanks @ripienaar, https://github.com/nats-io/nats.go/issues/616
