### ISSUE TITLE
JetStream stats api

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#413]
JetStream needs to expose monitoring data so that tooling can be built - surveyor etc

Some notes follow.

## Server wide JetStream data

Accessed over monitor port and via Request, when accessed within an account automatically limited to that account

### /jsz

 * Count of streams
 * Count of consumers
 * Disk Storage used in total
 * Memory Storage used in total
 * Total JS Messages in 
 * Time taken to commit messages to disk - will show cluster time in raft
 * Total JS Messages out
 * API Requests handled including acks etc
 * Time taken to handle API requests including acks etc - will show slowdowns in raft processing
 * API Error counts
 * Total expired messages
 * Total acked messages
 * Total redelivered messages
 * Raft blah blah no idea
 * Cluster info - all members in the metagroup and who is leader
 
### /jsz?state=1

  * all of above
  * For all streams for all accounts `[{"stream": "x", "account": "y", "state": {..StreamState..}}, ....]`with paging
  
`StreamState` should probably include which server is the API master for it and what servers own the storage, and some kind of raft sanity state flag

### /jsz?state=1&account=bob

 * all of above limited by account where appropriate

**Comment by derekcollison** [comment]
I think we should start with less, and I may say that if we do streams and consumers counts that we also group by account, not make flat list.

So would remove (for now)
  Time taken to commit
  Time taken on API
  Total Expired and Acked and Redelivered Messages

Would also suggest

{
  disk: B,
  memory: B,
  total_streams: N,
  total_consumers: N,
  accounts : {
    "$G" : [stream: streamInfo, ...]
  }

Although not sure if this should show specific stream info..

**Comment by ripienaar** [comment]
A lot of this has landed and we have quite good tooling, closing.
