### ISSUE TITLE
JetStream cluster api/cli

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jetstream#414]
# JetStream Cluster Admin

Some thoughts on things we'd want to be able to do, first on the nodes in question from the CLI and then over APIs

## Server CLI

This is the `nats-server`:

 - [x] join this node to a cluster, this is done by enabling JS in the config and restarting, or cli flag
 - [x] gracefully leave the cluster indicating this server will return later - done when the server goes into lame duck
 - [x] get RAFT states, cluster detail etc via the http monitor endpoint `/jsz`
 
## API

These are tasks an admin should be able to do. They are done via a NATS based API in the system account exposed in the `nats` CLI and a API in system account

Clustering is made up of many raft groups:

 * A meta raft group that all JS enabled servers belong to
 * Each stream has a raft group of servers that contribute to its storage
 * Each consumer has a raft group to manage its state
 

### Meta group related

 - [x] Evict a node, potentially forcibly. It's gone not coming back, should be able to be done with the node offline when forcing 
 - [x] Trigger lame duck on a specific server (graceful leave, does come back later)
 - [x] List memebers, states, etc this has to include enough to locate the actual unix node hosting the instance
 - [x] Server report showing all streams and consumers it is active in

### Stream related

 - [x] Move a specific stream off a given server - ie. leave the stream raft group indicating it's going away forever, new node will be elected and data migrated 
 - [x] List members, states, catchup state etc
 - [ ] Initiate a health check of all data like a snapshot does 
 
### Consumer related

 - [x] Move a specific consumer off a given server - ie. leave the stream raft group indicating it's going away forever, new node will be elected and data migrated
 - [x] List members, states, catchup state etc

## NATS CLI

So this adds:

```
nats s cluster step-down <stream>
nats s cluster peer-remove <stream> <peer>
nats c cluster step-down
nats server report jetstream [<serverid or name>]
nats server raft step-down
```

**Comment by derekcollison** [comment]
Realize that we return server name and cluster name in normal info when connecting, so I think we should add them into StreamInfo and ConsumerInfo if running in clustered mode, so won't always be there.

**Comment by gedw99** [comment]
Anyone know if this architecture roadmap / design wil require a dB for durable NATS Streaming server ? 

It would be awesome if the System using Raft was not reliant on a third party dB server and instead used a distributed WAL approach.

**Comment by ripienaar** [comment]
No database required, based on raft with shared-nothing architecture.  You can already try it today :)
