### ISSUE TITLE
does jetstream support message delay?

### ISSUE THREAD

**Issue by alifpay** [nats-io/jetstream#417]
Is it possible publish/subscribe message with time delay.. ? 

Message timers let you specify an initial invisibility period for a message added to a queue. For example, if you send a message with a 45-second timer, the message isn't visible to consumers for its first 45 seconds in the queue. The default (minimum) delay for a message is 0 seconds.

**Comment by ripienaar** [comment]
no we dont have such a feature, mind explaining the use case a bit?

**Comment by alifpay** [comment]
We have an external API, sometimes it doesn't respond, after a while we try to send it again ... if our app is in one replica, that's not a problem, we get from the database and send it. but if we have more than one replica, the request will be more than one and it is problem..

**Comment by ripienaar** [comment]
You can use the duplicate tracking in jetstream to allow multiple publishes but only 1 going into the stream, would that not address the concern of the more than 1 replica?

**Comment by alifpay** [comment]
it is OK! We are using Queue Subscribe in nats streaming, but need a message to delay.. I tested with nats streaming to resend. it is very fast and it is very overwhelmed.
