### ISSUE TITLE
In pull mode, sending an AckNak does not request a new message

### ISSUE THREAD

**Issue by acroca** [nats-io/jetstream#423]
Hi,

I'm following the 'tutorial' with ORDERS stream and NEW consumer filtering `ORDERS.received`.

To consume the consumer I have the following:
```
ch := make(chan *nats.Msg, 10)
subs, _ := js.ChanSubscribe("ORDERS.received", ch, nats.PullDirect("ORDERS", "NEW", 2))

for {
  msg, _ := subs.NextMsg(5 * time.Second)
  go handle(msg, nc)
}

func handle(msg *nats.Msg, nc *nats.Conn) {
  time.Sleep(300 * time.Millisecond)
  msg.Respond(nats.AckNak)
}
```

So it handles in pull-mode with a batch size of 2. There's only one message in the consumer during the test run.

This is expected to run forever, as it naks every time, but it's doing it only twice.

The tracing from the nats-server looks like the following:

```
<<- [CONNECT {"verbose":false,"pedantic":false,"tls_required":false,"name":"","lang":"go","version":"1.11.0","protocol":1,"echo":true,"headers":true,"no_responders":true}]
<<- [PING]
->> [PONG]
<<- [SUB _INBOX.dJaIkTcNSAClhvqVPNuv5c.*  1]
<<- [PUB $JS.API.INFO _INBOX.dJaIkTcNSAClhvqVPNuv5c.0eD0urHH 0]
<<- MSG_PAYLOAD: [""]
->> [MSG _INBOX.dJaIkTcNSAClhvqVPNuv5c.0eD0urHH 1 239]
<<- [PUB ORDERS.received _INBOX.dJaIkTcNSAClhvqVPNuv5c.5ZziCcXS 7]
<<- MSG_PAYLOAD: ["Hello 0"]
->> [MSG _INBOX.dJaIkTcNSAClhvqVPNuv5c.5ZziCcXS 1  27]
<<- [PUB $JS.API.CONSUMER.INFO.ORDERS.NEW _INBOX.dJaIkTcNSAClhvqVPNuv5c.YSb4t6zQ 0]
<<- MSG_PAYLOAD: [""]
->> [MSG _INBOX.dJaIkTcNSAClhvqVPNuv5c.YSb4t6zQ 1 651]
<<- [SUB _INBOX.dJaIkTcNSAClhvqVPNuv9n  2]
<<- [PUB $JS.API.CONSUMER.MSG.NEXT.ORDERS.NEW _INBOX.dJaIkTcNSAClhvqVPNuv9n 11]
<<- MSG_PAYLOAD: ["{\"batch\":2}"]
->> [MSG ORDERS.received 2 $JS.ACK.ORDERS.NEW.1.1.1.1611214888881598823.0 7]
<<- [PUB $JS.ACK.ORDERS.NEW.1.1.1.1611214888881598823.0 4]
<<- MSG_PAYLOAD: ["-NAK"]
->> [MSG ORDERS.received 2 $JS.ACK.ORDERS.NEW.2.1.2.1611214888881598823.0 7]
<<- [PUB $JS.ACK.ORDERS.NEW.2.1.2.1611214888881598823.0 4]
<<- MSG_PAYLOAD: ["-NAK"]
```

And from there it just reaches the 5 seconds timeout.

It seems the server is not sending more messages once it reaches the batch size (Tried changing the batch size and we just get as many as the batch size states)

Is this expected? Do I have to send anything else after the nak to get more messages?

Also, as a side note, using `msg.Nak()` ([implementation](https://github.com/nats-io/nats.go/blob/7fb8bacca6134844180ecf488295f1b998d431d9/js.go#L838-L839)) sends a `+NXT` which I believe is wrong, isn't it? 

Thank you.

**Comment by ripienaar** [comment]
One for @wallyqs i think, he has been working on the new clients

**Comment by acroca** [comment]
I did the same experiment using `AckAck` and same issue happens, no more messages are delivered. So I think what I'd need is some sort of `AckNakNext`, where it naks the message and requests a new one. Does it make sense?

**Comment by ripienaar** [comment]
Hmm, I thought we had a way to append next info to the NAK but appears not anyway lets see what @wallyqs suggests a bit later

**Comment by acroca** [comment]
From the [server code](https://github.com/nats-io/nats-server/blob/5d7e69b5402c09888b3dfd6787bc324fd34b74e5/server/consumer.go#L932-L957) I don't think that's possible. But I might be missing something.

**Comment by acroca** [comment]
Shall I open individual issues in https://github.com/nats-io/nats.go for the client 'bug' (`.AckNak()` doesn't send NAK in pull mode) and https://github.com/nats-io/nats-server (nak can't request next message)?

**Comment by ripienaar** [comment]
yes please

**Comment by acroca** [comment]
Done!

https://github.com/nats-io/nats-server/issues/1844
https://github.com/nats-io/nats.go/issues/641

**Comment by acroca** [comment]
Any updates on this? This is blocking us from continuing our migration to JetStream.

**Comment by ripienaar** [comment]
Sorry, will look into it today

**Comment by acroca** [comment]
Thank you, I really appreciate.
