### ISSUE TITLE
State of dead letter queues

### ISSUE THREAD

**Issue by acroca** [nats-io/jetstream#425]
Hi,

We'd like to know what's the state of discussion around DLQs. We're migrating from SQS to Jetstream and DLQ is an essential part of our messaging system.

If DLQs is not something that will be available any time soon, what workaround to get a similar functionality would be recommended?

**Comment by ripienaar** [comment]
While we do not support a DLQ in the traditional way - it's a bit different in a stream vs a message queue - we do publish advisories about messages that reach their max delivery, these advisories include Stream name and sequence, consumer name and sequence giving you all the information you need to pin point the problem message.

In a traditional DLQ the message MOVES to the DLQ, in streams the same message can be consumed by many consumers at different times and for different needs, so we publish pointers to problem messages.

See under https://github.com/nats-io/jetstream#advisories, look for the `Consumer maximum delivery reached` and `Message delivery terminated using AckTerm` ones

**Comment by ripienaar** [comment]
See for example `nats schema show io.nats.jetstream.advisory.v1.max_deliver`

**Comment by acroca** [comment]
Oh, I didn't know about those advisories. It sounds like it'd work.

I'm thinking about having a stream and consumer listening to the `max delivery reached` subjects from the advisories so it'll create a consumer with pointers to those messages, so whoever processes the DLQ can get those pointers and read the specific messages. It sounds like the same as a DLQ to me, isn't it? Does that make sense?

**Comment by ripienaar** [comment]
That's the intended use yes, exactly. If you need to persist them just set a stream up to ingest those topics and you're done.

```nats event``` can show them event :)
