### ISSUE TITLE
feature: List All Consumers via Jetstream Admin API

### ISSUE THREAD

**Issue by jon-whit** [nats-io/jetstream#435]
I'd like to be able to `$JS.API.CONSUMER.LIST` (or similar) to list all consumers (regardless of the stream they belong to) and get back a paginated list of the consumers. 

```
[
  { "stream_name": "somestream", "consumer_info": {...} },
  { "stream_name": "otherstream", "consumer_info": {...} }
]
```

or maybe even organized by stream name

```
[
  {
      "stream_name": "somestream",
      "consumers": [
          {...consumerInfo},
          {...consumerInfo}
      ]
  },
  {
      "stream_name": "otherstream",
      "consumers": [
          ....
      ]
  }
]
```

**Comment by ripienaar** [comment]
@derekcollison what do you think? I think the work in #413 will probably address this need, in any event I'd do this after that one only should we decide to do it

**Comment by derekcollison** [comment]
Not sure this is tied to /jsz work since this would be API based access.

Right now this would be N + 1 queries to the system, first getting stream list then asking for the consumer list/info for each. Unless there is an expectation that there will be very large N I think this is ok for now.

Just curious, when wanting all of the consumers together is this for operations purposes or something else?

**Comment by ripienaar** [comment]
The data in `/jsz` would be available over nats as well as a request interface, thats why I was thinking we'd see how that shake out first.  I imagine for monitoring access in the account - scoped to the account - we'd place the monitor request under `$JS.API` as well.

**Comment by derekcollison** [comment]
Remember though, you would need to query all servers in the cluster/supercluster w/ JS enabled and piece all that information together. So yes agree should be available this is a multiple response and aggregation point with the /jsz only approach.

**Comment by ripienaar** [comment]
We already do that in surveyor so thats possible, but I suspect how jsz works in a cluster - certainly the NATS Request based one - needs a very careful think through

**Comment by derekcollison** [comment]
I think so, at least I know I need to a bit more ;)

**Comment by ripienaar** [comment]
In my view the meta controller has to be the only one that respond and it gives us a cluster view for the case of requesting it over nats...that'll be fun

**Comment by derekcollison** [comment]
That is what happens today. If this API were introduced it would function the same as stream and consumer names/list work now.

**Comment by jon-whit** [comment]
@derekcollison my use case right now is basically just to maintain a metadata catalog of existing consumer info. I'm building an application on top of Jetstream that would benefit from this information, and it'd be nice if the API exposed a way to list all (and even filter would be nice in some cases) instead of requiring a client to execute the N + 1 query against the API. Since that information is already readily available (making an assumption here) on the server, it makes sense to me to expose that level of info in a single API call.

**Comment by ripienaar** [comment]
JSZ can do this - though its a ton of data.  `nats server req jsz --leader --trace --all`
