### ISSUE TITLE
#JetStream#LeafNode Support?

### ISSUE THREAD

**Issue by wchajl** [nats-io/jetstream#440]
I test 2 jetStreams in leafnode mode connecting to a JetStream cluster(one node),only to find the behavior is very confused.
My configurations is as below ：
```
server_name : server1

jetstream {
	store_dir : $server_name
	max_mem : 1Gb
	max_file : 5Gb
}

cluster {
	name : JSC
	listen:0.0.0.0:6222
	routes : [
		nats://0.0.0.0:6222
	]
}
leafnodes {
	listen : 0.0.0.0:7422
}
```

```
server_name : test1
listen : 0.0.0.0:4222

jetstream {
    store_dir : $server_name
    max_mem : 1Gb
    max_file : 5Gb
}

leafnodes {
    remotes : [
        {url : "nats://10.110.105.4:7422"}
    ]
}
```
```
server_name : test2
listen : 0.0.0.0:4222

jetstream {
    store_dir : $server_name
    max_mem : 1Gb
    max_file : 5Gb
}

leafnodes {
    remotes : [
        {url : "nats://10.110.105.12:7422"}
    ]
}

```

+ Test1 & test2 are in VMs and server1 is a cloude server.test1 & test2 are not in a cluster while server1 is in a one node cluster.
1.  It seems that test1 & test2 share the same stream and consumer ,and both of them hold a replica of stream. Deleting stream on one node will delete the other's same stream too.(they are much like in a cluster)
2. msg published on test1\test2\server1 can be received with consumer in every node.
3. server1 can only pub msgs & received msg from test1&test2 with pull mode consumer.Server1 have no access in its only stream\consumer.``nats: error: could not select Stream: JetStream system temporarily unavailable``

+ I get pretty much confused in this. Did you have a plan or what's you design of jetstream in leafnode mode? Looking forward to your reply.Thanks!

**Comment by ripienaar** [comment]
What you set up is probably 2 isolated jetstream instances in tbe same account with no clustering. So that won’t work. 

At present while we are working on clustering the only clustered option is to enable it on every node in a cluster. 

You can join leafnodes as you try but each leafnode must provide jetstream to a different account so any account has only 1 JS instance

**Comment by wchajl** [comment]
But does that means if there are  200 edge deveices ,I have to create 200 extra accounts ? If so ,it would be hard to manage it .In some cloud-edge cases,we want to use jetstream as a buffer while the network is broken,once network recovers ,the tranport resumes.

**Comment by wchajl** [comment]
> What you set up is probably 2 isolated jetstream instances in tbe same account with no clustering. So that won’t work.
> 
> At present while we are working on clustering the only clustered option is to enable it on every node in a cluster.
> 
> You can join leafnodes as you try but each leafnode must provide jetstream to a different account so any account has only 1 JS instance

But does that means if there are 200 edge deveices ,I have to create 200 extra accounts ? If so ,it would be hard to manage it .In some cloud-edge cases,we want to use jetstream as a buffer while the network is broken,once network recovers ,the tranport resumes.

**Comment by ripienaar** [comment]
What kind of devices? Generaly you use leafnodes to put connections near devices, not a leafnode per device but depends on your needs.

We're at the moment focussed on a JS per account and those form RAFT groups, you almost certainly would not want to do join edge leafnodes to any raft groups.  Eventually you can have a local JetStream and it will replicate to central jetstream using mirroring tech so it will function independently and offline.

**Comment by wchajl** [comment]
> What kind of devices? Generaly you use leafnodes to put connections near devices, not a leafnode per device but depends on your needs.
> 
> We're at the moment focussed on a JS per account and those form RAFT groups, you almost certainly would not want to do join edge leafnodes to any raft groups. Eventually you can have a local JetStream and it will replicate to central jetstream using mirroring tech so it will function independently and offline.

For example, some outdoor devices with multipul sensors to collect information like temperature,etc. We want our  app to communicate with  an inner jetstream to deal with network conditions ,and messages are send to central server by jetstream .The central server does not have direct access to edge devieces,so I reckon that  leafnode is the best opt .In my design ,every device has its own jetstream and only send the information in need to the centrol server,and we can just put a client to pull msg from centrol server.May be a local-scale account that works only for one leafnode could solve this problem(every leafnode is restricted to certain subject).

**Comment by ripienaar** [comment]
OK, then what we're planning will work for you, right now while we're working on clustering this is not supported but should hopefully be by GA

**Comment by wchajl** [comment]
I will continue  with accounts configuration first ,and forward to the GA.Thanks!
