### ISSUE TITLE
NATS Account Server Support?

### ISSUE THREAD

**Issue by nfrush** [nats-io/jetstream#441]
Does JetStream currently support external auth (i.e. nats-account-server)? I've hooked up a JetStream node successfully to the nats-account-server, but I'm seeing "Jetstream not enabled for this account". Is there instructions for enabling Jetstream when external auth is enabled?

**Comment by ripienaar** [comment]
I believe you also need the nightly nsc and a master build of account server. @matthiashanel can give the full details

**Comment by matthiashanel** [comment]
@nfrush external auth via nats-account-server should be working. However jetstream options are made available by using an unreleased version of nsc. You need to get that from either our nightly images or build it from source. Once upgraded you should be able to set jetstream options on your accounts. 

One thing to be aware about is that after you upgraded your nsc, it is going to ask you to migrate your operator.

**Comment by nfrush** [comment]
@matthiashanel Hmm... so I've upgraded nsc and nats-account-server and I can see that I've enabled Jetstream on the account (SYS). However, whenever I use "nats --creds {{file path}} account info", I get back that jetstream is not enabled for account. Is there anything special I need to do there?

**Comment by nfrush** [comment]
This works :)

**Comment by matthiashanel** [comment]
@nfrush sorry, completely missed your earlier response. You have to enable jetstream in your account by setting either memory or disk limit to a value other than 0 and pushing your change. This command sets all jetstream limits to unlimited `nsc edit account --name EXP-CONS  --mem-storage -1 --streams -1 --consumer -1 --disk-storage -1`
