### ISSUE TITLE
cannot create clusters on Nats CLI

### ISSUE THREAD

**Issue by Soypete** [nats-io/jetstream#453]
Hello, I was trying to get Jetstream working with my go app and I requires a `ClusterID`. When trying to add a cluster stream I received this error. 
```nats: error: unknown long flag '--replicas', try --help```
These are the steps takes:

```
docker run -ti -p 4222:4222 --name jetstream synadia/jsm:latest server
nats str ls
nats str add CHATS --replicas 3
```
I am running on MacOS BigSur. 
I installed the tools as recommended my the readme
```
brew tap nats-io/nats-tools
brew install nats-io/nats-tools/nats
```

I was able to connect to Nats via `nats.Connect`, but not using the github.com/nats-io/stan.go

**Comment by ripienaar** [comment]
At present while we're working on Clustering we're adding clustering related features almost daily, so the --replicas option is only in the nightly builds - the container with the server also has latest nats cli

If you did `docker run -ti --link jetstream synadia/jsm:latest` you can use the nats cli in there
