### ISSUE TITLE
Dart client  for Flutter Web and Flutter native supported ?

### ISSUE THREAD

**Issue by gedw99** [nats-io/jetstream#499]
Found 3 here.

https://pub.dev/packages?q=Nats

would be awesome if the NATS team supports an official library for flutter native ( tcp ) and flutter web ( I presume web sockets and so could use the existing nats ja with a simple wrapper 

At the moment we have wrapped nats with GRPC so as to support many different client languages but the new semantics of Jetstream are such that GRPC is not so useful anymore with nats.

@wallyqs ?

**Comment by ripienaar** [comment]
We had some requests already for this but its not on the immediate short list I am afraid
