### ISSUE TITLE
Clients

### ISSUE THREAD

**Issue by winwisely99** [nats-io/jetstream#92]
Is there a dart client ? That's what I am interested in.

Or how would someone make a client ?

Jetstream seems to support pull and push.
So then can I presume that grpc can be used to wrap Jetstream consumer API ?

Grpc would make things reusable for many clients

**Comment by ripienaar** [comment]
There might be others but I saw https://github.com/c16a/nats-dart, JetStream doesnt need any special clients so you could use an existing core nats on like that.

There might be others, @ColinSullivan1 might know?

**Comment by winwisely99** [comment]
thanks @ripienaar 

The other option i have is to embed the golang client inside Flutter.
Then we are not reliant on Dart client for NATS.

Good example on the cocept is  here: https://github.com/deromask/deromask
- this works fully on Desktop and Mobile by using gomobile and embedding this.
- Protobufs are used between gomobile and Flutter layers.

Would appreciate and thoughts on this also...

**Comment by ripienaar** [comment]
If you can embed go stuff in flutter then that sounds like a winner :)

**Comment by winwisely99** [comment]
Cheers. Will give it a go and let you know how we get on.

Thanks for your advice

**Comment by ripienaar** [comment]
Closing this one, feel free to open another issue if you have more questions :)

**Comment by gedw99** [comment]
@ripienaar 

The latest NATS Dart cleint is this one btw:

https://github.com/chartchuo/dart-nats

Its reaching maturity slowly. We might help. Not sure yet

**Comment by winwisely99** [comment]
@ripienaar 

https://github.com/c16a/nats-dart is very old and incomplete

https://github.com/chartchuo/dart-nats looks to be getting close to feature complete.

We might help. Nit sure yet though as we are reviewing options.

**Comment by ColinSullivan1** [comment]
Help would be greatly appreciated, and we'd welcome another contribution in this area.  I'm not aware of any other dart client beyond the ones mentioned above.

**Comment by winwisely99** [comment]
@ColinSullivan1 

We have isolated 3 approaches:
1. Get on board and help the dart NATS client
2. Embed the NATS go client via go-mobile
3 wrap the NATS server with GRPC 

Option 3 looks like the most interoperable.
We need an untyped interoperability solution because our funders and users are orgs using a variety of languages. By wrapping NATS server side it will allow their microserices to easily talk to the  gateway as well as the flutter client to talk to the gateway.

I wonder if Jetstream will be moving to a grpc based API ?

**Comment by ColinSullivan1** [comment]
I'd think #1 or #2 would be ideal.

gRPC does have a lot of language bindings, but you lose location transparency, failover functionality, and NATS does have true multi-tenancy that can help you manage the orgs connecting to you.  NATS does a multitude of client types...   https://nats.io/download/#nats

JetStream won't have a gRPC interface; it'll use core NATS.
