### ISSUE TITLE
README Discrepancies

### ISSUE THREAD

**Issue by sfrooster** [nats-io/jetstream#96]
I'm running both the latest server and jsm from docker.

A few differences I noticed between expected results as shown in the README vs what I encountered, some positive (in my opinion), others which may be attributable to out of date documentation, or changed or broken behavior.  My apologies for not splitting these out into separate issues though, to be fair, they may just all be documentation issues:

- after creating a stream `jsm str add ORDERS`, the documentation indicates the configuration will [report](https://github.com/nats-io/jetstream/blob/master/README.md#creating) `No Acknowledgements: false` but actually reports (the improved) `Acknowledgements: true`  (PR [here](https://github.com/nats-io/jetstream/pull/95) probably not comprehensive)

- this [section](https://github.com/nats-io/jetstream#publishing-into-a-stream) says that executing `nats-pub ORDERS.scratch hello` will return/display `Published [sub1] : 'hello'` but in fact nothing is displayed. (`jsm str info ORDERS` does show there is now a message in the stream)

- the README next demo's using nats-req with `nats-req ORDERS.scratch hello` and shows we should receive a `+OK` but, instead I receive a usage message:
`Usage: nats-req [-s server] [-creds file] [-t] <subject> <request>
  -creds string
    	User Credentials File
  -h	Show help message
  -s string
    	The NATS System (default "connect.ngs.global")
  -t	Display timestamps
  -v	Show version`

- The example which begins with `jsm con add --sample 100` shows a configuration output with an entry of `Deliver Last: false` after `Deliver All: true`, but the `Deliver Last` entry is not present in the actual run.

- Similar to the note two points up, `nats-req '$JS.NEXT.ORDERS.DISPATCH' ''` returns a nats-req usage message rather than `Published [$JS.NEXT.ORDERS.DISPATCH] : ''
Received  [ORDERS.processed] : 'order 3'` as indicated

**Comment by ripienaar** [comment]
cool - we have an number of these nats-req/nats-sub/nats-pub commands and alas not all are equally blessed, I've been meaning to update the ones in the JSM binary with better ones - or maybe the underlying natsbox ones which are awful.

Will check out these updates thank you!

**Comment by sfrooster** [comment]
Now using `synadia/jsm:0.0.8`, it seems that point 3 above (`nats-req ORDERS.scratch hello` does not respond with `+OK`) has been "fixed" as it does now respond with `+OK`.

**Comment by ripienaar** [comment]
> Now using `synadia/jsm:0.0.8`, it seems that point 3 above (`nats-req ORDERS.scratch hello` does not respond with `+OK`) has been "fixed" as it does now respond with `+OK`.

hmm, that tells me something else is going on, i didnt touch that between these releases.

**Comment by sfrooster** [comment]
It was late - maybe I misreported the problem initially?

**Comment by ripienaar** [comment]
could be :)

**Comment by ripienaar** [comment]
Closing as we moved to new docs and much have changed in a year :)
