### ISSUE TITLE
jq does not come installed with synadia/jsm:0.0.8

### ISSUE THREAD

**Issue by sfrooster** [nats-io/jetstream#99]
The use of `jq` as mentioned [here](https://github.com/nats-io/jetstream#editing) fails because `jq` is not installed.  I was able to download it myself with `wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64` and otherwise run that example.

**Comment by ripienaar** [comment]
indeed, I think I am mainly using it there to hone in on the specific detail rather than get distracted with the rest of the orders output (and then later I have less to update too :P)

I can add it if you think it would be useful though

**Comment by sfrooster** [comment]
Depends on your priorities I think.  Avoiding image bloat seems reasonable and it's only used in that one place. You could add some verbiage - I've submitted a PR...

**Comment by ripienaar** [comment]
closing via #101
